# Generated by Django 2.2.7 on 2020-03-18 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('admin_name', models.CharField(max_length=30, verbose_name='用户名')),
                ('admin_password', models.CharField(max_length=20, verbose_name='密码')),
                ('admin_phone', models.CharField(default='13771000000', max_length=11, verbose_name='手机号')),
                ('user_type', models.IntegerField(choices=[(1, '系统管理员'), (2, '活动负责人'), (3, '学生')], default=1, verbose_name='用户类型')),
                ('admin_status', models.IntegerField(choices=[(1, '已注册'), (0, '未注册')], default=1, verbose_name='管理员状态')),
            ],
            options={
                'verbose_name': '系统管理员',
                'verbose_name_plural': '系统管理员',
            },
        ),
        migrations.CreateModel(
            name='Chargers',
            fields=[
                ('charger_id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('charger_name', models.CharField(max_length=30, verbose_name='用户名')),
                ('charger_password', models.CharField(max_length=20, verbose_name='密码')),
                ('user_type', models.IntegerField(choices=[(1, '系统管理员'), (2, '活动负责人'), (3, '学生')], default=2, verbose_name='用户类型')),
                ('charger_phone', models.CharField(default='13771000000', max_length=11, verbose_name='手机号码')),
                ('charger_status', models.IntegerField(choices=[(1, '已注册'), (0, '未注册')], default=1, verbose_name='负责人状态')),
            ],
            options={
                'verbose_name': '老师',
                'verbose_name_plural': '老师',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('class_name', models.CharField(max_length=50, verbose_name='班级名称')),
                ('class_status', models.IntegerField(choices=[(1, '已注册'), (0, '未注册')], default=1, verbose_name='班级状态')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('department_name', models.CharField(max_length=50, verbose_name='学院名称')),
                ('department_status', models.IntegerField(choices=[(1, '已注册'), (0, '未注册')], default=1, verbose_name='学院状态')),
            ],
            options={
                'verbose_name': '学院',
                'verbose_name_plural': '学院',
            },
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('school_name', models.CharField(max_length=50, verbose_name='学校名称')),
                ('school_status', models.IntegerField(choices=[(1, '已注册'), (0, '未注册')], default=1, verbose_name='学校状态')),
            ],
            options={
                'verbose_name': '学校',
                'verbose_name_plural': '学校',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('student_no', models.CharField(max_length=20, verbose_name='学号')),
                ('student_name', models.CharField(max_length=30, verbose_name='学生姓名')),
                ('student_password', models.CharField(max_length=20, verbose_name='密码')),
                ('student_phone', models.CharField(default='13771000000', max_length=11, verbose_name='手机号')),
                ('user_type', models.IntegerField(choices=[(1, '系统管理员'), (2, '活动负责人'), (3, '学生')], default=3, verbose_name='用户类型')),
                ('student_status', models.IntegerField(choices=[(1, '已注册'), (0, '未注册')], default=1, verbose_name='学生状态')),
                ('classes', models.ForeignKey(db_constraint=django.db.models.deletion.CASCADE, on_delete=django.db.models.deletion.CASCADE, to='logManager.Classes', verbose_name='所属班级')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='StudentToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logManager.Students')),
            ],
        ),
        migrations.CreateModel(
            name='Majors',
            fields=[
                ('major_id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('major_name', models.CharField(max_length=50, verbose_name='专业名称')),
                ('major_status', models.IntegerField(choices=[(1, '已注册'), (0, '未注册')], default=1, verbose_name='专业状态')),
                ('department', models.ForeignKey(db_constraint=django.db.models.deletion.CASCADE, on_delete=django.db.models.deletion.CASCADE, to='logManager.Departments', verbose_name='所属学院')),
            ],
            options={
                'verbose_name': '专业',
                'verbose_name_plural': '专业',
            },
        ),
        migrations.AddField(
            model_name='departments',
            name='school',
            field=models.ForeignKey(db_constraint=django.db.models.deletion.CASCADE, on_delete=django.db.models.deletion.CASCADE, to='logManager.Schools', verbose_name='所属学校'),
        ),
        migrations.AddField(
            model_name='classes',
            name='major',
            field=models.ForeignKey(db_constraint=django.db.models.deletion.CASCADE, on_delete=django.db.models.deletion.CASCADE, to='logManager.Majors', verbose_name='所属专业'),
        ),
        migrations.CreateModel(
            name='ChargeToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logManager.Chargers')),
            ],
        ),
        migrations.AddField(
            model_name='chargers',
            name='school',
            field=models.ForeignKey(db_constraint=django.db.models.deletion.CASCADE, on_delete=django.db.models.deletion.CASCADE, to='logManager.Schools', verbose_name='所属学校'),
        ),
        migrations.CreateModel(
            name='AdminToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logManager.Admins')),
            ],
        ),
        migrations.AddField(
            model_name='admins',
            name='school',
            field=models.ForeignKey(db_constraint=django.db.models.deletion.CASCADE, on_delete=django.db.models.deletion.CASCADE, to='logManager.Schools', verbose_name='所属学校'),
        ),
    ]
