# Generated by Django 2.2.7 on 2020-02-25 19:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0010_patient_p_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False, verbose_name='病房号')),
                ('room_name', models.CharField(max_length=20, verbose_name='病房名称')),
                ('room_capacity', models.IntegerField(verbose_name='容纳人数')),
            ],
            options={
                'verbose_name': '病房',
                'verbose_name_plural': '病房',
            },
        ),
        migrations.CreateModel(
            name='RoomBed',
            fields=[
                ('bed_id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('bed_name', models.CharField(max_length=10, verbose_name='床号')),
                ('bed_status', models.IntegerField(default=0, verbose_name='状态')),
                ('room', models.ForeignKey(db_constraint=django.db.models.deletion.CASCADE, on_delete=django.db.models.deletion.CASCADE, to='ward.Room', verbose_name='所属病房')),
            ],
            options={
                'verbose_name': '病床',
                'verbose_name_plural': '病床',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='病房类型编号')),
                ('type_name', models.CharField(max_length=30, verbose_name='病房类型')),
            ],
            options={
                'verbose_name': '病房类型',
                'verbose_name_plural': '病房类型',
            },
        ),
        migrations.CreateModel(
            name='RoomPatien',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('checkin_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='入住时间')),
                ('checkout_time', models.DateTimeField(auto_now=True, null=True, verbose_name='出院时间')),
                ('status', models.IntegerField(verbose_name='状态')),
                ('bed', models.ForeignKey(db_constraint=django.db.models.deletion.CASCADE, on_delete=django.db.models.deletion.CASCADE, to='ward.RoomBed', verbose_name='床号')),
                ('patient', models.ForeignKey(db_constraint=django.db.models.deletion.CASCADE, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='病人')),
            ],
            options={
                'verbose_name': '入住表',
                'verbose_name_plural': '入住表',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(db_constraint=django.db.models.deletion.CASCADE, on_delete=django.db.models.deletion.CASCADE, to='ward.RoomType', verbose_name='病房类型'),
        ),
    ]
