# Generated by Django 2.2.7 on 2020-02-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roompatien',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
    ]
