# Generated by Django 2.2.7 on 2020-02-25 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treat', '0003_treat_treat_status'),
        ('ward', '0002_auto_20200225_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='roompatien',
            name='treat',
            field=models.ForeignKey(db_constraint=django.db.models.deletion.CASCADE, default=6, on_delete=django.db.models.deletion.CASCADE, to='treat.Treat', verbose_name='出诊记录'),
            preserve_default=False,
        ),
    ]
