# Generated by Django 2.2.7 on 2020-02-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0003_roompatien_treat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roompatien',
            name='checkin_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='入住时间'),
        ),
    ]
