# Generated by Django 2.2.7 on 2020-03-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_status',
            field=models.IntegerField(choices=[(1, '已注册'), (0, '未注册')], default=1, verbose_name='公告状态'),
        ),
    ]
