# Generated by Django 2.2.7 on 2020-03-20 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logManager', '0001_initial'),
        ('activities', '0002_auto_20200318_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
        migrations.AddField(
            model_name='activities',
            name='school',
            field=models.ForeignKey(db_constraint=django.db.models.deletion.CASCADE, default=1, on_delete=django.db.models.deletion.CASCADE, to='logManager.Schools', verbose_name='所属学校'),
            preserve_default=False,
        ),
    ]
