# Generated by Django 2.2.7 on 2020-03-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logManager', '0001_initial'),
        ('activities', '0003_auto_20200320_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='charger',
            field=models.ManyToManyField(to='logManager.Chargers'),
        ),
    ]
