# Generated by Django 2.2.7 on 2020-03-20 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logManager', '0001_initial'),
        ('activities', '0005_remove_activities_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='charger',
        ),
        migrations.AddField(
            model_name='activities',
            name='charger',
            field=models.ForeignKey(db_constraint=django.db.models.deletion.CASCADE, default=1, on_delete=django.db.models.deletion.CASCADE, to='logManager.Chargers', verbose_name='活动负责人'),
            preserve_default=False,
        ),
    ]
