# Generated by Django 2.2.7 on 2020-03-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20200320_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuedntActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('singin_status', models.IntegerField(choices=[(0, '未签'), (1, '已签')], default=0, verbose_name='签到状态')),
                ('singout_status', models.IntegerField(choices=[(0, '未签'), (1, '已签')], default=0, verbose_name='签退状态')),
                ('credit', models.IntegerField(default=0, verbose_name='获得学分')),
            ],
        ),
    ]
