# Generated by Django 2.2.7 on 2020-03-20 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logManager', '0001_initial'),
        ('activities', '0007_stuedntactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuedntactivity',
            name='activity_id',
            field=models.ForeignKey(db_constraint=django.db.models.deletion.CASCADE, default=1, on_delete=django.db.models.deletion.CASCADE, to='activities.Activities', verbose_name='活动编号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stuedntactivity',
            name='student_id',
            field=models.ForeignKey(db_constraint=django.db.models.deletion.CASCADE, default=1, on_delete=django.db.models.deletion.CASCADE, to='logManager.Students', verbose_name='学生编号'),
            preserve_default=False,
        ),
    ]
