# Generated by Django 2.2.7 on 2020-03-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_auto_20200321_0513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stuedntactivity',
            old_name='singin_status',
            new_name='signin_status',
        ),
        migrations.RenameField(
            model_name='stuedntactivity',
            old_name='singout_status',
            new_name='signout_status',
        ),
    ]
