# Generated by Django 2.2.7 on 2020-04-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_auto_20200322_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuedntactivity',
            name='credit',
            field=models.FloatField(default=0, verbose_name='获得学分'),
        ),
    ]
