# Generated by Django 2.2.7 on 2020-02-19 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('type_name', models.CharField(max_length=10, verbose_name='类型')),
            ],
            options={
                'verbose_name': '类型',
                'verbose_name_plural': '类型',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('doc_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('doc_password', models.CharField(max_length=20, verbose_name='密码')),
                ('doc_birth', models.DateField(verbose_name='生日')),
                ('doc_gender', models.IntegerField(verbose_name='性别')),
                ('doc_age', models.IntegerField(verbose_name='年龄')),
                ('doc_email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('doc_address', models.CharField(max_length=100, verbose_name='地址')),
                ('doc_phone', models.TextField(max_length=13, verbose_name='手机')),
                ('doc_type', models.ForeignKey(db_constraint=django.db.models.deletion.CASCADE, on_delete=django.db.models.deletion.CASCADE, to='doctor.DoctorType', verbose_name='类型')),
            ],
            options={
                'verbose_name': '医生',
                'verbose_name_plural': '医生',
            },
        ),
    ]
