# Generated by Django 2.2.7 on 2020-02-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_phone',
            field=models.CharField(max_length=13, verbose_name='手机'),
        ),
    ]
