# Generated by Django 2.2.7 on 2020-02-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20200219_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doc_age',
        ),
    ]
