# Generated by Django 2.2.7 on 2020-02-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_doctor_doc_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doc_experience',
            field=models.IntegerField(default=5, verbose_name='执业时间'),
        ),
    ]
