# Generated by Django 2.2.7 on 2020-02-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctor_doc_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_experience',
            field=models.IntegerField(verbose_name='执业时间'),
        ),
    ]
