# Generated by Django 2.2.7 on 2020-02-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_doctor_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doc_image',
            field=models.ImageField(default='1.png', upload_to='doctor-headers', verbose_name='照片'),
        ),
    ]
