# Generated by Django 2.2.7 on 2020-02-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_doctor_doc_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_image',
            field=models.ImageField(default='default.jpg', upload_to='doctor-headers', verbose_name='照片'),
        ),
    ]
