# Generated by Django 2.2.7 on 2020-02-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_auto_20200221_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_image',
            field=models.ImageField(upload_to='doctor-headers', verbose_name='照片'),
        ),
    ]
