# Generated by Django 2.2.7 on 2020-02-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_auto_20200224_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doc_active',
            field=models.IntegerField(default=1, verbose_name='医生激活状态'),
        ),
    ]
