# Generated by Django 2.2.7 on 2019-12-03 19:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False, verbose_name='收货地址id')),
                ('address_content', models.CharField(max_length=100, verbose_name='收货地址')),
                ('address_status', models.IntegerField(default=1, verbose_name='收货地址状态')),
            ],
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('delivery_id', models.AutoField(max_length=100, primary_key=True, serialize=False, verbose_name='骑手id')),
                ('delivery_name', models.CharField(max_length=100, verbose_name='骑手登录名')),
                ('delivery_password', models.CharField(max_length=32, verbose_name='密码')),
                ('delivery_mobile', models.CharField(max_length=13)),
                ('delivert_status', models.IntegerField(default=1, verbose_name='骑手id')),
                ('delivert_image', models.ImageField(default='default.jpeg', upload_to='delivery/%Y/%m', verbose_name='骑手头像')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_id', models.AutoField(max_length=100, primary_key=True, serialize=False, verbose_name='用户id')),
                ('goods_name', models.CharField(max_length=100, verbose_name='用户名')),
                ('goods_number', models.IntegerField(verbose_name='商品数量')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('goods_discount', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='商品折扣')),
                ('goods_description', models.CharField(max_length=100, verbose_name='商品描述')),
                ('goods_status', models.IntegerField(default=1, verbose_name='商品状态')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('type_id', models.AutoField(max_length=100, primary_key=True, serialize=False, verbose_name='主营类型id')),
                ('type_name', models.CharField(max_length=100, verbose_name='主营类型')),
                ('type_status', models.IntegerField(default=1, verbose_name='主营类型状态')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('user_name', models.CharField(max_length=32, verbose_name='用户名')),
                ('user_password', models.CharField(max_length=32, verbose_name='密码')),
                ('user_pay_password', models.CharField(max_length=11, null=True, verbose_name='支付密码')),
                ('user_mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('user_status', models.IntegerField(default=1, verbose_name='用户状态')),
                ('user_image', models.ImageField(default='default.jpeg', upload_to='user/%Y/%m', verbose_name='用户头像')),
                ('user_face', models.CharField(max_length=100, null=True, verbose_name='用户人脸地址')),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False, verbose_name='商家id')),
                ('seller_name', models.CharField(max_length=100, verbose_name='商家名称')),
                ('seller_image', models.ImageField(default='default.jpeg', upload_to='seller/%Y/%m', verbose_name='商家头像')),
                ('seller_start', models.CharField(max_length=100, verbose_name='每日开店时间')),
                ('seller_end', models.CharField(max_length=100, verbose_name='每日打样时间')),
                ('seller_regist_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='商家注册时间')),
                ('seller_status', models.IntegerField(default=1, verbose_name='商家状态')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Types')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(max_length=100, primary_key=True, serialize=False, verbose_name='id')),
                ('order_name', models.CharField(max_length=100, verbose_name='订单编号')),
                ('order_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单金额')),
                ('order_time', models.DateTimeField(verbose_name='下单时间')),
                ('order_status', models.IntegerField(default=1, verbose_name='订单状态')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Address')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Deliveries')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Sellers')),
            ],
        ),
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('detail_id', models.AutoField(max_length=100, primary_key=True, serialize=False, verbose_name='订单详情id')),
                ('goods_count', models.IntegerField(verbose_name='商品数量')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Orders')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Sellers'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Users'),
        ),
    ]
