# Generated by Django 2.2.7 on 2019-12-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers',
            name='seller_nums',
            field=models.IntegerField(default=0, max_length=100, verbose_name='销量'),
        ),
    ]
