# Generated by Django 2.2.7 on 2019-12-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_sellers_seller_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_image',
            field=models.ImageField(default='static/head_images/goods/default.jpeg', upload_to='goods/%Y/%m', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='seller_nums',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
    ]
