# Generated by Django 2.2.7 on 2019-12-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191209_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_reamrk',
            field=models.CharField(default='', max_length=100, verbose_name='订单备注'),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='delivery_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='骑手id'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='detail_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='订单详情id'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='types',
            name='type_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='主营类型id'),
        ),
    ]
