# Generated by Django 2.2.7 on 2019-12-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20191210_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers',
            name='seller_password',
            field=models.CharField(default='123456789', max_length=100, verbose_name='商家密码'),
        ),
    ]
