# Generated by Django 2.2.7 on 2019-12-10 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_sellers_seller_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='seller_end',
            field=models.CharField(max_length=100, null=True, verbose_name='每日打样时间'),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='seller_name',
            field=models.CharField(max_length=100, null=True, verbose_name='商家名称'),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='seller_start',
            field=models.CharField(max_length=100, null=True, verbose_name='每日开店时间'),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Types'),
        ),
    ]
