# Generated by Django 2.2.7 on 2020-02-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treat',
            name='treat_active',
            field=models.IntegerField(default=1, verbose_name='治疗激活状态'),
        ),
    ]
