# Generated by Django 2.2.7 on 2020-02-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treat', '0002_treat_treat_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='treat',
            name='treat_status',
            field=models.IntegerField(default=1, verbose_name='治疗状态'),
        ),
    ]
