# Generated by Django 2.2.7 on 2020-02-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('president', '0002_auto_20200219_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('type_name', models.CharField(max_length=50, verbose_name='类型')),
            ],
        ),
    ]
