# Generated by Django 2.2.7 on 2020-02-20 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('president', '0003_usertype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertype',
            options={'verbose_name': '用户类型', 'verbose_name_plural': '用户类型'},
        ),
    ]
