# Generated by Django 2.2.7 on 2019-11-28 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('uinf_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('uinf_nickname', models.CharField(max_length=32, verbose_name='昵称')),
                ('uinf_email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('uinf_sex', models.CharField(max_length=4, verbose_name='性别')),
                ('uinf_mobile', models.CharField(max_length=11, verbose_name='手机号码')),
                ('uinf_url', models.CharField(max_length=100, verbose_name='个人博客地址')),
                ('unit_intoduction', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('user_name', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('user_password', models.CharField(max_length=32, verbose_name='密码')),
                ('userDetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.UserDetail')),
            ],
        ),
    ]
