# Generated by Django 2.2.7 on 2019-11-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userdetail_uinf_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='unit_intoduction',
            new_name='unif_intoduction',
        ),
    ]
