# Generated by Django 2.2.7 on 2019-11-28 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191128_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='unif_intoduction',
            new_name='uinf_intoduction',
        ),
    ]
