# Generated by Django 2.2.7 on 2019-11-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191128_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='uinf_intoduction',
            new_name='uinf_introduction',
        ),
    ]
