# Generated by Django 2.2.7 on 2019-11-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191128_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='uinf_introduction',
            new_name='uinf_sign',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='uinf_sex',
            field=models.CharField(default='保密', max_length=4, verbose_name='性别'),
        ),
    ]
