# Generated by Django 2.2.7 on 2019-11-29 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191128_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='uinf_nickname',
        ),
    ]
