# Generated by Django 2.2.7 on 2019-11-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191129_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='uinf_avatar',
            field=models.ImageField(blank=True, default='blog/avatar/default.png', max_length=200, null=True, upload_to='avatar/%Y/%m', verbose_name='用户头像'),
        ),
    ]
