# Generated by Django 2.2.7 on 2019-11-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_article_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='article',
            name='art_title',
            field=models.CharField(max_length=30, verbose_name='标题'),
        ),
    ]
