# Generated by Django 2.2.7 on 2019-11-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20191129_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='art_content',
            field=models.TextField(max_length=30, verbose_name='正文'),
        ),
    ]
