# Generated by Django 2.2.7 on 2019-11-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20191130_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='art_content',
            field=models.TextField(verbose_name='正文'),
        ),
    ]
