# Generated by Django 2.2.7 on 2020-02-21 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('president', '0005_president_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('status_name', models.CharField(max_length=50, verbose_name='状态')),
            ],
            options={
                'verbose_name': '病人状态',
                'verbose_name_plural': '病人状态',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('p_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('p_password', models.CharField(max_length=20, verbose_name='密码')),
                ('p_birth', models.DateField(verbose_name='生日')),
                ('p_gender', models.IntegerField(verbose_name='性别')),
                ('p_email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('p_address', models.CharField(max_length=100, verbose_name='地址')),
                ('p_phone', models.CharField(max_length=13, verbose_name='手机')),
                ('p_status', models.ForeignKey(blank=True, db_constraint=django.db.models.deletion.CASCADE, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.PatientStatus', verbose_name='状态')),
                ('user_type', models.ForeignKey(db_constraint=django.db.models.deletion.CASCADE, default=3, on_delete=django.db.models.deletion.CASCADE, to='president.UserType', verbose_name='类型')),
            ],
            options={
                'verbose_name': '病人',
                'verbose_name_plural': '病人',
            },
        ),
    ]
