# Generated by Django 2.2.7 on 2020-02-21 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='p_status',
            field=models.ForeignKey(db_constraint=django.db.models.deletion.CASCADE, default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.PatientStatus', verbose_name='状态'),
        ),
    ]
