# Generated by Django 2.2.7 on 2020-02-23 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_auto_20200221_1026'),
        ('patient', '0002_auto_20200221_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('reg_time', models.DateTimeField(auto_now=True, verbose_name='挂号时间')),
                ('reg_status', models.IntegerField(default=1, verbose_name='状态')),
                ('reg_patient', models.ForeignKey(db_constraint=django.db.models.deletion.CASCADE, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='病人姓名')),
                ('reg_type', models.ForeignKey(db_constraint=django.db.models.deletion.CASCADE, on_delete=django.db.models.deletion.CASCADE, to='doctor.DoctorType', verbose_name='挂号类型')),
            ],
            options={
                'verbose_name': '挂号表',
                'verbose_name_plural': '挂号表',
            },
        ),
    ]
