# Generated by Django 2.2.7 on 2020-02-24 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20200223_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='reg_patient',
            field=models.ForeignKey(db_constraint=django.db.models.deletion.CASCADE, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='病人编号'),
        ),
    ]
